# Generated by Django 4.1.2 on 2022-10-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_urlsshortener_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsshortener',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
