# Generated by Django 4.1.1 on 2022-11-07 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_urlsshortener_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsshortener',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 20, 26, 52, 56648)),
        ),
    ]
