// AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";
export const LOGOUT = "LOGOUT";

//OPERATIONS
export const URL_SHORTENING_SUCCESS = "URL_SHORTENING_SUCCESS";
export const URL_SHORTENING_FAIL = "URL_SHORTENING_FAIL";
export const GET_ALL_URLS_SUCCESS = "GET_ALL_URLS_SUCcESS";
export const GET_ALL_URLS_FAIL = "GET_ALL_URLS_FAIL";
export const GET_URL_BY_ID_SUCCESS = "GET_URL_BY_ID_SUCCESS";
export const GET_URL_BY_ID_FAIL = "GET_ALL_URLS_FAIL";
export const UPDATE_URL_SUCCESS = "UPDATE_URL_SUCCESS";
export const UPDATE_URL_FAIL = "UPDATE_ALL_URLS_FAIL";
